name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: nftestgha
        # Container registry password
        password: ${{ secrets.SuperSecret }}
        # Container registry server url
        login-server: nftestgha.azurecr.io
    - name: Build and push
      run: |
        docker build . -t contoso.azurecr.io/k8sdemo:${{ github.sha }}
        docker push contoso.azurecr.io/k8sdemo:${{ github.sha }}
